server:
  port: 9999

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: CoderHome-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.157.172.249:3306/coder?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: System.MySQL
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #空闲连接最大超时时间 2分钟
      max-lifetime: 120000

  #kenife4j 配置
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  #token加盐
  key: JGKFDSAJGLDJSALKGJIOWGJEOIWJJGIODSJAGIODJS
  #token过期时间
  timeout: 30